#!/usr/bin/php

<?php

require_once('vendor/autoload.php');
require_once('config.php');

class ProjectBuilder
{
	private $scenario = [];
	private $args = [];
	private $result = [];

	public function __construct($args)
	{
		$this->args = $args;
	}

	public function applyToAllRepo($cmd, $params = '')
	{
		$path = 'vendor/follower/';
		exec('cd ' . $path . ' && ls', $projects);

		array_unshift($projects, '');

		foreach ($projects as $project) {
			if ($cmd == 'add') {
				$this->runCmd($path . $project, $cmd, $params);
			} else {
				$this->printString();
				$this->printString('+------------------------------');
				$this->printString('| ' . ($project ? 'follower/' . $project : 'main'));
				$this->printString('+------------------------------');
				$this->printString($this->runCmd($path . $project, $cmd, $params));
			}
		}
	}

	public function execute()
	{
		switch ($this->args[1]) {
			case 'status' :
				$this->applyToAllRepo($this->args[1]);
				break;

			case 'reset' :
				$this->applyToAllRepo($this->args[1], $this->args[2]);
				break;

			case 'push' :
			case 'pull' :
				if (empty($this->args[2])) {
					$this->args[2] = 'origin';
				}
				if (empty($this->args[3])) {
					$this->args[3] = 'master';
				}
				$this->applyToAllRepo($this->args[1], $this->args[2] . ' ' . $this->args[3]);
				break;

			case 'check' :
				$this->checkSyntaxErrors();
				break;

			case 'commit' :
				if (isset($this->args[2])) {
					$this->applyToAllRepo('add', '.');
					$this->applyToAllRepo('commit -am \'' . $this->args[2] . '\'');
				} else {
					$this->result[] = 'Enter commit reason';
				}
				break;

			case 'schema:update':
				$paths = ['vendor/follower/core/backend'];
				if (isset($this->args[2])) {
					$paths[] = $this->args[2];
				}
				\Core\Database\Schema::createObjects($paths);
				break;

			case 'schema:create':
				if (!isset($this->args[2])) {
					return false;
				}
				\Core\Database\Schema::createObject($this->args[2], ['clearDb' => true]);
				break;

			case 'help' :
			default :
				$this->result = [
					'Project Builder v 1.1',
					'Git aggregator commands:',
					' * commit \'commit reason\' - commits changes to current branch',
					' * status - \'git status\' output',
					' * push - \'git push\' to all repositories',
					' * pull - \'git pull\' from all repositories',
					'Schema commands:',
					' * schema:update \'project\' - clears db and recreate schema',
					' * schema:create \'object\' - creates table for specified object',
				];
				break;
		}

		$this->resultOutput();
	}

	private function checkSyntaxErrors()
	{
		$root = getcwd();
		$dir = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root));

		foreach ($dir as $path => $fileInfo) {
			$results = [];
			if ($fileInfo->isFile() && $fileInfo->getExtension() === 'php') {
				exec('php -l ' . $fileInfo->getPathname(), $results);
			}

			foreach($results as $result) {
				if (preg_match("/^No syntax errors detected.*$/", $result)) {
					$this->printString($result, 'green');
				} else {
					$this->printString($result, 'red');
				}
			}
		}
	}

	private function printString($text = '', $color = false)
	{
		switch($color) {
			case 'green':
				echo "\033[32m $text \033[0m" . PHP_EOL;
				break;
			case 'red':
				echo "\033[31m $text \033[0m" . PHP_EOL;
				break;
			default:
				echo $text . PHP_EOL;
		}
	}

	private function runCmd($path, $command, $params = '')
	{
		if ($path) {
			$cd = 'cd ' . $path . ' && ';
		}

		exec($cd . 'git ' . $command . ' ' . $params, $result);
		return implode("\n", $result);
	}

	private function resultOutput()
	{
		array_walk($this->result, function ($line) {
			$this->printString($line);
		});
	}
}

$builder = new ProjectBuilder($argv);
$builder->execute();
